root: true

env:
    browser: true
    node: true

extends:
    - 'eslint:recommended'
    - 'plugin:vue/recommended'
    - '@nuxtjs/eslint-config-typescript'
    - 'plugin:prettier/recommended'

plugins:
    - vue

rules:
    indent: ['error', 4]
    vue/html-indent: ['error', 4]
